development:
  auth_token: 'secret'
  webpanel_database_password: 'secret'
production:
  auth_token: 'secret'
  webpanel_database_password: 'secret'
test:
  auth_token: 'secret'
  webpanel_database_password: 'secret'
